// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSqDNK4kj2VGUc7hgkwGVNLIj3oBRbXTQ',
    appId: '1:227040916026:web:8c747573d21483d4363b03',
    messagingSenderId: '227040916026',
    projectId: 'uni-student-tracker',
    authDomain: 'uni-student-tracker.firebaseapp.com',
    storageBucket: 'uni-student-tracker.firebasestorage.app',
    measurementId: 'G-DK9HCMHY3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-luUKGTaX9xoYXS2-pJEVOLYbrvcUxM',
    appId: '1:227040916026:android:734fcddc3771dd89363b03',
    messagingSenderId: '227040916026',
    projectId: 'uni-student-tracker',
    storageBucket: 'uni-student-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdhGIVIZU4Gl9CBbHMMo_lFaMnwcaOuys',
    appId: '1:227040916026:ios:982f7b586f16fb05363b03',
    messagingSenderId: '227040916026',
    projectId: 'uni-student-tracker',
    storageBucket: 'uni-student-tracker.firebasestorage.app',
    iosBundleId: 'com.example.nsbmStudentAcademicTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdhGIVIZU4Gl9CBbHMMo_lFaMnwcaOuys',
    appId: '1:227040916026:ios:982f7b586f16fb05363b03',
    messagingSenderId: '227040916026',
    projectId: 'uni-student-tracker',
    storageBucket: 'uni-student-tracker.firebasestorage.app',
    iosBundleId: 'com.example.nsbmStudentAcademicTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSqDNK4kj2VGUc7hgkwGVNLIj3oBRbXTQ',
    appId: '1:227040916026:web:214b345470135377363b03',
    messagingSenderId: '227040916026',
    projectId: 'uni-student-tracker',
    authDomain: 'uni-student-tracker.firebaseapp.com',
    storageBucket: 'uni-student-tracker.firebasestorage.app',
    measurementId: 'G-7LVQKEJHYY',
  );
}
